### ISSUE TITLE
Support for PHPStorm 9.0.2

### ISSUE THREAD

**Issue by franciscocabral** [cmazx/yiistorm#38]
I'm using PHPStorm 9.0.2 and would be great to have this plugin here. Can make it happens? 

![Screenshot](http://img.prntscr.com/img?url=http://i.imgur.com/bggxc70.png)

**Comment by cmazx** [comment]
what about remove it and re-install from repository?

**Comment by franciscocabral** [comment]
thanks it works.

I was downloading the jar file and adding to my ide.
