### ISSUE TITLE
Stopped working since PhpStorm 2018.2.5

### ISSUE THREAD

**Issue by benomatis** [cmazx/yiistorm#54]
Is it only me?

**Comment by cmazx** [comment]
well, i didnt support it at least two years)

**Comment by benomatis** [comment]
I'm suspicious it's not with your plugin, actually, that still works: I get undefined variable and method not found errors in inspection instead, so I posted in the community, hope it will help me (and others): https://intellij-support.jetbrains.com/hc/en-us/community/posts/360001409019-MVC-Inspection-undefined-variable-in-view-method-not-found-in-child-class
